# Generated by Django 3.2.6 on 2021-11-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingContentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('PostingContents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_image', to='post_api.postingcontents')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
