# Generated by Django 3.2.5 on 2021-12-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contentsimage',
            table='contents_image',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
