# Generated by Django 3.2.5 on 2021-11-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_alter_project_end_date'),
        ('post_api', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='project_api.project'),
        ),
    ]
