# Generated by Django 3.2.5 on 2022-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='Post_bookmark',
        ),
        migrations.AlterModelTable(
            name='contentsimage',
            table='Post_image',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Post_like',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post_posting',
        ),
    ]
