# Generated by Django 3.2.5 on 2021-12-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0003_auto_20211221_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='post_api.post'),
        ),
    ]
