# Generated by Django 3.2.5 on 2022-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0004_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
