# Generated by Django 3.2.5 on 2022-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='user',
        ),
    ]
