# Generated by Django 3.1.3 on 2022-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='member',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
