# Generated by Django 3.2.5 on 2022-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='diff_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sum_id',
        ),
        migrations.AddField(
            model_name='room',
            name='member',
            field=models.JSONField(default={}),
        ),
    ]
