# Generated by Django 3.2.5 on 2022-01-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220111_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
