# Generated by Django 3.2.5 on 2022-01-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_msg_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='receiver',
            new_name='receiver_id',
        ),
    ]
