# Generated by Django 3.2.5 on 2022-01-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_receiver_msg_receiver_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
