# Generated by Django 3.2.6 on 2021-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
