# Generated by Django 3.2.5 on 2022-01-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question_api.question'),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='Q_answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Q_question',
        ),
    ]
