# Generated by Django 3.2.5 on 2022-01-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_api', '0004_auto_20220104_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pquestion',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2pquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
