# Generated by Django 3.2.5 on 2022-01-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0006_auto_20220104_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2pquestion',
            name='to',
        ),
        migrations.RemoveField(
            model_name='p2pquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='P2PAnswer',
        ),
        migrations.DeleteModel(
            name='P2PQuestion',
        ),
    ]
