# Generated by Django 3.2.5 on 2022-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0008_auto_20220203_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
