# Generated by Django 3.2.5 on 2022-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0009_auto_20220207_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
