# Generated by Django 3.2.5 on 2022-03-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0001_initial'),
        ('question_api', '0001_initial'),
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Question_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tag', to='question_api.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_tag', to='tag.tag')),
            ],
            options={
                'db_table': 'Q_tag',
            },
        ),
        migrations.CreateModel(
            name='Project_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='project_api.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_tag', to='tag.tag')),
            ],
            options={
                'db_table': 'Proj_tag',
            },
        ),
        migrations.CreateModel(
            name='Profile_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tag', to='user_api.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_tag', to='tag.tag')),
            ],
            options={
                'db_table': 'Prof_tag',
            },
        ),
    ]
