# Generated by Django 3.2.5 on 2022-06-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Tag',
        ),
    ]
