# Generated by Django 3.2.5 on 2021-11-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0002_alter_answer_question'),
        ('tag', '0002_alter_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tag', to='question_api.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_tag', to='tag.tag')),
            ],
            options={
                'db_table': 'question_tag',
            },
        ),
    ]
