# Generated by Django 3.2.5 on 2022-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_question_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile_tag',
            table='Prof_tag',
        ),
        migrations.AlterModelTable(
            name='project_tag',
            table='Proj_tag',
        ),
        migrations.AlterModelTable(
            name='question_tag',
            table='Q_tag',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
