# Generated by Django 3.2.5 on 2022-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0002_auto_20220203_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
