# Generated by Django 3.2.5 on 2021-11-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loopship',
            old_name='second',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='loopship',
            old_name='first',
            new_name='user',
        ),
    ]
