# Generated by Django 3.2.5 on 2022-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loopship',
            table='Loopship',
        ),
        migrations.AlterModelTable(
            name='request',
            table='Loop_request',
        ),
    ]
