# Generated by Django 3.2.5 on 2021-11-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_tag_tagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
