# Generated by Django 3.2.5 on 2022-01-04 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_num', models.CharField(max_length=10)),
                ('corp_name', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_inform', to='user_api.profile')),
            ],
            options={
                'db_table': 'Corp_inform',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_num', models.CharField(max_length=10)),
                ('corp_name', models.TextField()),
                ('email', models.TextField()),
                ('name', models.CharField(max_length=10)),
                ('tel_num', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Corp_active',
            },
        ),
    ]
