# Generated by Django 3.2.5 on 2022-01-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_activation_company_inform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
