# Generated by Django 3.2.5 on 2021-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='기타', max_length=15),
        ),
    ]
