# Generated by Django 3.2.5 on 2021-12-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='class_num',
        ),
    ]
