# Generated by Django 3.2.5 on 2021-12-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_auto_20211231_1321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company_inform',
            table='company_inform',
        ),
    ]
