# Generated by Django 3.2.5 on 2022-01-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0010_auto_20220104_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_inform',
            name='profile',
        ),
    ]
