# Generated by Django 3.2.5 on 2022-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
