# Generated by Django 3.2.5 on 2022-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Get_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Get_log',
            },
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_list', models.JSONField(default=dict)),
                ('user_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'Interest_tag',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('query', models.TextField()),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Search_Log',
            },
        ),
    ]
