# Generated by Django 3.2.5 on 2022-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesttag',
            name='tag_list',
            field=models.JSONField(default=dict),
        ),
    ]
