# Generated by Django 3.2.5 on 2022-01-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connect_log',
        ),
    ]
