# Generated by Django 3.2.5 on 2022-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20220214_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Get_log',
            },
        ),
        migrations.AlterField(
            model_name='interesttag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
