# Generated by Django 3.2.5 on 2021-11-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
