# Generated by Django 3.2.6 on 2021-11-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crew',
            name='start_date',
            field=models.DateField(),
        ),
    ]
