# Generated by Django 3.2.5 on 2022-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='introduction',
        ),
    ]
