# Generated by Django 3.2.5 on 2022-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_remove_project_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
