# Generated by Django 3.2.6 on 2021-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_alter_project_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
