# Generated by Django 3.2.5 on 2021-12-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_taglooper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taglooper',
            old_name='user',
            new_name='looper',
        ),
    ]
