# Generated by Django 3.2.5 on 2021-12-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0005_rename_user_taglooper_looper'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taglooper',
            table='LooperTag',
        ),
    ]
