# Generated by Django 3.2.5 on 2021-12-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_api', '0006_alter_taglooper_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglooper',
            name='looper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taglooper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looper', to='project_api.project'),
        ),
    ]
