# Generated by Django 3.2.5 on 2021-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0007_auto_20211221_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pj_thumbnail',
            field=models.ImageField(default=True, null=True, upload_to=''),
        ),
    ]
