# Generated by Django 3.2.5 on 2021-12-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0008_project_pj_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pj_thumbnail',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
