# Generated by Django 3.1.3 on 2022-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0011_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pj_thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='project/%Y%m%d/'),
        ),
    ]
